version: '3'
services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile-mvn
    image: shadow1212/spring_mvc:1.2
    container_name: spring_mvc
    tty: true
    volumes:
      - ./:/app/
    ports:
      - "8080:8080"
